export const SHOW_CART_PANEL = 'SHOW_CART_PANEL';
export const HIDE_CART_PANEL = 'HIDE_CART_PANEL';

export const RESET_CART = "RESET_CART"

export const ADD_PRODUCT_INTO_CART = 'ADD_PRODUCT_INTO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const SHOW_CHECKOUT_MODAL = "SHOW_CHECKOUT_MODAL"
export const HIDE_CHECKOUT_MODAL = "HIDE_CHECKOUT_MODAL"
